#!/bin/bash
PARENT_COMMAND="$(ps -o comm= $PPID)"
if [ "$PARENT_COMMAND" == "java" ]; then 
	exec docker exec haskell /opt/dockerbaseddev/haskell/docker-wrapper/inside/ghc-wrapper $(pwd) $@
else
	exec docker exec -i haskell /opt/dockerbaseddev/haskell/docker-wrapper/inside/ghc-wrapper $(pwd) $@
fi
