FROM fpco/stack-build
MAINTAINER jkramarz@virtuslab.com
RUN useradd -m developer -s /usr/bin/bash -u 1000
USER developer
VOLUME /opt/dockerbaseddev
WORKDIR /opt/dockerbaseddev
ENV HOME /home/developer
