#!/usr/bin/env bash
[ -d $1 ] && cd $1
shift
if [ "$1" == "--numeric-version" ]; then
	exec cabal $@
else
	echo echo "${@: -1}"
	echo "Running in container, PWD=$(pwd)"	1>&2
	set -vx
	exec cabal ${@##--with-ghc=*}
fi
